server:
  port: 5000
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: service-zuul
zuul:
  routes:
    hiapi:
      path: /hiapi/**
      #      serviceId: eureka-client
      url: http://localhost:8763/
    feignapi:
      path: /feignapi/**
      serviceId: eureka-feign-client
    ribbonapi:
      path: /ribbonapi/**
      serviceId: eureka-ribbon-client
  prefix: /v1